version: "2.1"

services:
  frontend:
    container_name: ${PROJECT_NAME}_frontend
    build: ./frontend
    volumes:
      - "./frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "${FRONTEND_PORT}:5000"

  backend:
    container_name: ${PROJECT_NAME}_backend
    build: ./backend
    volumes:
      - "./backend:/usr/src/app"
      - "./backend/package.json:/usr/src/package.json"
    ports:
      - "${BACKEND_PORT}:8080"
